services:
  redis:
      image: redis:7
      container_name: redis
      ports:
        - "6379:6379"
  carpooling-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    env_file:
      - .env
    volumes:
      - carpooling-logs:/app/winston
      - /app/node_modules
      - .:/app
    depends_on:
      - redis

  

volumes:
  carpooling-logs:
    